name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "8563ca6b2fce7007d1f19beeb40ae923"
main = "src/index.ts"
workers_dev = false

# 如果没使用自定义域名，将BASE_URL改为 worker 的默认路由
vars = { ENVIRONMENT = "production", BASE_URL = "https://gmonster.win" }

# 如果不使用自定义域名，将下面的代码注释掉
route = { pattern = "gmonster.win", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "02f2dfcf059440c1af4aa257921b4dcf" },
]

[site]
bucket = "./static/dist"


[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'pastes'
